name: Publish container image

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: log in to Docker Hub
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSER }}
          password: ${{ secrets.DOCKERHUBTOKEN }}
      - name: Creat Docker image tags
        id: metadata
      - uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/api-health
          tags: |
            type=sha,prefix=
            type=raw,value=latest
      - name: Build and publish Docker image
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
